name: Continuous integration
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    - cron: '0 2 * * *'
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12, 14, 16, 18, 20 ]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous integration
      run: npm run debug-test
  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12, 14, 16, 18, 20 ]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm i

    - name: Continuous integration
      run: npm run debug-test
